Algoritmo "MaiorQueDez"
// Crie um programa que descubra se um valor informado pelo usuário
//é maior ou menor que 10. Exiba na tela o resultado com uma mensagem amigável.

Var
   numero : inteiro

Inicio
      escreval("Maior que Dez")
      escreva("Informe um número: ")
      leia(numero)
      se numero > 10 entao
            escreval("Número maior que 10")
      senao
            escreval("Número menor ou igual à 10")
      fimse

Fimalgoritmo