Algoritmo "Exercicio3"
// Use a estrutura de repetição enquanto condição
// faz para mostrar uma contagem de números
// pares na tela. Essa contagem deve iniciar
// em 0 e terminar com um número previamente
// informado pelo usuário.

Var
   i , numeroFinal : inteiro

Inicio
   escreva("Informe um número final: ")
   leia(numeroFinal)

   enquanto i <= numeroFinal faca
      escreval(i)
      i := i + 2
   fimenquanto

Fimalgoritmo