Algoritmo "Multiplicação"
// Faça um algoritmo para somar dois números informados pelo usuário
//e multiplicar o resultado pelo primeiro número.


Var
   numero1, numero2, resultado : real

Inicio
      escreval("Multiplicação")
      escreva("Informe um número: ")
      leia(numero1)
      escreva("Informe um número: ")
      leia(numero2)
      resultado := (numero1 + numero2) * numero1
      escreva("Resultado ", resultado)
Fimalgoritmo