Algoritmo "Procedimentos"

Var
   n1 , n2 : inteiro

procedimento soma(valor1 , valor2 : inteiro)
inicio

   escreva("Resultado da Soma:")
   escreval(valor1+valor2)

fimprocedimento

procedimento subtracao(valor1 , valor2 : inteiro)
inicio
   escreva("Resultado da Subtração: ")
   escreval(valor1-valor2)
fimprocedimento

Inicio
   soma(10,20)
   soma(10,3)
   soma(7,3)
   subtracao(10,3)

Fimalgoritmo